# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouTubeClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouTubeClone
    pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
    pod 'Google/SignIn', '~> 3.0.3'
end
